base_features =[
 'DebtRatio',
 'MonthlyIncome',
 'NumberOfDependents',
 'NumberOfOpenCreditLinesAndLoans',
 'NumberOfTime30-59DaysPastDueNotWorse',
 'NumberOfTime60-89DaysPastDueNotWorse',
 'NumberOfTimes90DaysLate',
 'NumberRealEstateLoansOrLines',
 'RevolvingUtilizationOfUnsecuredLines',
 'age']

delinquency_features = [
 'NumberOfTime30-59DaysPastDueNotWorse',
 'NumberOfTime60-89DaysPastDueNotWorse',
 'NumberOfTimes90DaysLate']

socio_demo_features = [ 'MonthlyIncome', 'NumberOfDependents','age', 'cluster_group']

credit_features = [
 'DebtRatio',
 'NumberOfOpenCreditLinesAndLoans',
 'NumberOfTime30-59DaysPastDueNotWorse',
 'NumberOfTime60-89DaysPastDueNotWorse',
 'NumberOfTimes90DaysLate',
 'NumberRealEstateLoansOrLines',
 'RevolvingUtilizationOfUnsecuredLines'
]

added_features = ['CategoryEncoded_MonthlyIncome_max_DebtRatio',
 'CategoryEncoded_MonthlyIncome_max_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_MonthlyIncome_max_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_MonthlyIncome_max_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_MonthlyIncome_max_NumberOfTimes90DaysLate',
 'CategoryEncoded_MonthlyIncome_max_NumberRealEstateLoansOrLines',
 'CategoryEncoded_MonthlyIncome_max_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_MonthlyIncome_mean_DebtRatio',
 'CategoryEncoded_MonthlyIncome_mean_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_MonthlyIncome_mean_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_MonthlyIncome_mean_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_MonthlyIncome_mean_NumberOfTimes90DaysLate',
 'CategoryEncoded_MonthlyIncome_mean_NumberRealEstateLoansOrLines',
 'CategoryEncoded_MonthlyIncome_mean_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_MonthlyIncome_min_DebtRatio',
 'CategoryEncoded_MonthlyIncome_min_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_MonthlyIncome_min_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_MonthlyIncome_min_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_MonthlyIncome_min_NumberOfTimes90DaysLate',
 'CategoryEncoded_MonthlyIncome_min_NumberRealEstateLoansOrLines',
 'CategoryEncoded_MonthlyIncome_min_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_MonthlyIncome_std_DebtRatio',
 'CategoryEncoded_MonthlyIncome_std_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_MonthlyIncome_std_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_MonthlyIncome_std_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_MonthlyIncome_std_NumberOfTimes90DaysLate',
 'CategoryEncoded_MonthlyIncome_std_NumberRealEstateLoansOrLines',
 'CategoryEncoded_MonthlyIncome_std_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_NumberOfDependents_max_DebtRatio',
 'CategoryEncoded_NumberOfDependents_max_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_NumberOfDependents_max_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_NumberOfDependents_max_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_NumberOfDependents_max_NumberOfTimes90DaysLate',
 'CategoryEncoded_NumberOfDependents_max_NumberRealEstateLoansOrLines',
 'CategoryEncoded_NumberOfDependents_max_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_NumberOfDependents_mean_DebtRatio',
 'CategoryEncoded_NumberOfDependents_mean_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_NumberOfDependents_mean_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_NumberOfDependents_mean_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_NumberOfDependents_mean_NumberOfTimes90DaysLate',
 'CategoryEncoded_NumberOfDependents_mean_NumberRealEstateLoansOrLines',
 'CategoryEncoded_NumberOfDependents_mean_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_NumberOfDependents_min_DebtRatio',
 'CategoryEncoded_NumberOfDependents_min_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_NumberOfDependents_min_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_NumberOfDependents_min_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_NumberOfDependents_min_NumberOfTimes90DaysLate',
 'CategoryEncoded_NumberOfDependents_min_NumberRealEstateLoansOrLines',
 'CategoryEncoded_NumberOfDependents_min_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_NumberOfDependents_std_DebtRatio',
 'CategoryEncoded_NumberOfDependents_std_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_NumberOfDependents_std_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_NumberOfDependents_std_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_NumberOfDependents_std_NumberOfTimes90DaysLate',
 'CategoryEncoded_NumberOfDependents_std_NumberRealEstateLoansOrLines',
 'CategoryEncoded_NumberOfDependents_std_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_age_max_DebtRatio',
 'CategoryEncoded_age_max_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_age_max_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_age_max_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_age_max_NumberOfTimes90DaysLate',
 'CategoryEncoded_age_max_NumberRealEstateLoansOrLines',
 'CategoryEncoded_age_max_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_age_mean_DebtRatio',
 'CategoryEncoded_age_mean_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_age_mean_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_age_mean_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_age_mean_NumberOfTimes90DaysLate',
 'CategoryEncoded_age_mean_NumberRealEstateLoansOrLines',
 'CategoryEncoded_age_mean_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_age_min_DebtRatio',
 'CategoryEncoded_age_min_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_age_min_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_age_min_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_age_min_NumberOfTimes90DaysLate',
 'CategoryEncoded_age_min_NumberRealEstateLoansOrLines',
 'CategoryEncoded_age_min_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_age_std_DebtRatio',
 'CategoryEncoded_age_std_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_age_std_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_age_std_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_age_std_NumberOfTimes90DaysLate',
 'CategoryEncoded_age_std_NumberRealEstateLoansOrLines',
 'CategoryEncoded_age_std_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_cluster_group_max_DebtRatio',
 'CategoryEncoded_cluster_group_max_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_cluster_group_max_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_cluster_group_max_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_cluster_group_max_NumberOfTimes90DaysLate',
 'CategoryEncoded_cluster_group_max_NumberRealEstateLoansOrLines',
 'CategoryEncoded_cluster_group_max_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_cluster_group_mean_DebtRatio',
 'CategoryEncoded_cluster_group_mean_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_cluster_group_mean_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_cluster_group_mean_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_cluster_group_mean_NumberOfTimes90DaysLate',
 'CategoryEncoded_cluster_group_mean_NumberRealEstateLoansOrLines',
 'CategoryEncoded_cluster_group_mean_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_cluster_group_min_DebtRatio',
 'CategoryEncoded_cluster_group_min_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_cluster_group_min_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_cluster_group_min_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_cluster_group_min_NumberOfTimes90DaysLate',
 'CategoryEncoded_cluster_group_min_NumberRealEstateLoansOrLines',
 'CategoryEncoded_cluster_group_min_RevolvingUtilizationOfUnsecuredLines',
 'CategoryEncoded_cluster_group_std_DebtRatio',
 'CategoryEncoded_cluster_group_std_NumberOfOpenCreditLinesAndLoans',
 'CategoryEncoded_cluster_group_std_NumberOfTime30-59DaysPastDueNotWorse',
 'CategoryEncoded_cluster_group_std_NumberOfTime60-89DaysPastDueNotWorse',
 'CategoryEncoded_cluster_group_std_NumberOfTimes90DaysLate',
 'CategoryEncoded_cluster_group_std_NumberRealEstateLoansOrLines',
 'CategoryEncoded_cluster_group_std_RevolvingUtilizationOfUnsecuredLines',
 'DebtRatio MonthlyIncome',
 'DebtRatio NumberOfDependents',
 'DebtRatio NumberOfOpenCreditLinesAndLoans',
 'DebtRatio NumberOfTime30-59DaysPastDueNotWorse',
 'DebtRatio NumberRealEstateLoansOrLines',
 'DebtRatio RevolvingUtilizationOfUnsecuredLines',
 'DebtRatio age',
 'DebtRatio^2',
 'DependentsPerAge',
 'IncomeOverDebtRatio',
 'IncomePerAge',
 'IncomePerCreditLineLoan',
 'IncomePerDependent',
 'IncomePerRealEstateLoan',
 'LogDifference30to5960to89',
 'LogDifference60to8990plus',
 'MaxTotalTimesPastDue',
 'MeanTotalTimesPastDue',
 'MinTotalTimesPastDue',
 'MonthlyIncome NumberOfDependents',
 'MonthlyIncome NumberOfOpenCreditLinesAndLoans',
 'MonthlyIncome NumberOfTime30-59DaysPastDueNotWorse',
 'MonthlyIncome NumberRealEstateLoansOrLines',
 'MonthlyIncome RevolvingUtilizationOfUnsecuredLines',
 'MonthlyIncome age',
 'MonthlyIncome^2',
 'NumberOfDependents NumberOfOpenCreditLinesAndLoans',
 'NumberOfDependents RevolvingUtilizationOfUnsecuredLines',
 'NumberOfDependents age',
 'NumberOfOpenCreditLinesAndLoans NumberRealEstateLoansOrLines',
 'NumberOfOpenCreditLinesAndLoans RevolvingUtilizationOfUnsecuredLines',
 'NumberOfOpenCreditLinesAndLoans age',
 'NumberOfTime30-59DaysPastDueNotWorse RevolvingUtilizationOfUnsecuredLines',
 'NumberOfTime30-59DaysPastDueNotWorse age',
 'NumberRealEstateLoansOrLines RevolvingUtilizationOfUnsecuredLines',
 'NumberRealEstateLoansOrLines age',
 'PercentageNumberTimes30to59PastDue',
 'PercentageNumberTimes60to89PastDue',
 'PercentageNumberTimes90plusPastDue',
 'RealEstateLoansPerCreditLineLoan',
 'RevolvingUtilizationOfUnsecuredLines age',
 'RevolvingUtilizationOfUnsecuredLines^2',
 'StdTotalTimesPastDue',
 'SumTotalTimesPastDue',
 'SumTotalTimesPastDuePerCreditLineLoan',
 'UtilizationOverDebtRatio',
 'age^2',
 'cluster_group',
 'prediction_AdaBoostClassifier',
 'prediction_MLPClassifier',
 'prediction_RandomForestClassifier']

all_features_list = sorted(base_features + added_features)
